AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple CloudFront distribution for Streamlit application'

Parameters:
  StreamlitOriginIP:
    Type: String
    Default: 'streamlit-alb-1809216659.us-west-2.elb.amazonaws.com'
    Description: 'ALB DNS name for Streamlit app'

Resources:
  # CloudFront Distribution
  StreamlitCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: 'Ship Firefighting Rules Chatbot - Streamlit App'
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        
        # Origins
        Origins:
          - Id: streamlit-origin
            DomainName: !Ref StreamlitOriginIP
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        
        # Default Cache Behavior
        DefaultCacheBehavior:
          TargetOriginId: streamlit-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          Compress: false  # Disable compression for WebSocket
          
          # No caching for Streamlit dynamic content
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
          
          # Forward all headers for WebSocket support
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3  # AllViewer

Outputs:
  CloudFrontURL:
    Description: 'CloudFront Distribution URL'
    Value: !Sub 'https://${StreamlitCloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-URL'
  
  DistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref StreamlitCloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'